# Generated by Django 4.2.6 on 2023-10-24 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
                ('subscription_status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('law_firm', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
                ('subscription_status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('languages', models.ManyToManyField(to='core.languages')),
            ],
        ),
        migrations.CreateModel(
            name='Specialties_accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Specialties_lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accountant')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=255)),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_accountant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accountant')),
                ('reviewed_lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lawyer')),
            ],
        ),
        migrations.AddField(
            model_name='lawyer',
            name='specializations',
            field=models.ManyToManyField(to='core.specialties_lawyer'),
        ),
        migrations.AddField(
            model_name='accountant',
            name='languages',
            field=models.ManyToManyField(to='core.languages'),
        ),
        migrations.AddField(
            model_name='accountant',
            name='specializations',
            field=models.ManyToManyField(to='core.specialties_accountant'),
        ),
    ]
