# Generated by Django 4.2.6 on 2023-10-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountant',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='lawyer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='accountant',
            name='last_name',
            field=models.CharField(default='placeholder', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawyer',
            name='last_name',
            field=models.CharField(default='placeholder', max_length=255),
            preserve_default=False,
        ),
    ]
