# Generated by Django 4.2.6 on 2023-10-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_accountant_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountant',
            old_name='company_name',
            new_name='firm_name',
        ),
    ]
