# Generated by Django 4.2.6 on 2023-11-01 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_rename_company_name_accountant_firm_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('accountant', 'Accountant'), ('lawyer', 'Lawyer')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('law_firm', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
                ('subscription_status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('languages', models.ManyToManyField(to='core.languages')),
            ],
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialtiesAccountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.professional')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.specialties')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialtiesLawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.professional')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.specialties')),
            ],
        ),
        migrations.RemoveField(
            model_name='accountant',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='accountant',
            name='specializations',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewed_accountant',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewed_lawyer',
        ),
        migrations.DeleteModel(
            name='Lawyer',
        ),
        migrations.DeleteModel(
            name='Specialties_accountant',
        ),
        migrations.DeleteModel(
            name='Specialties_lawyer',
        ),
        migrations.AddField(
            model_name='professional',
            name='specialties',
            field=models.ManyToManyField(to='core.specialties'),
        ),
        migrations.AddField(
            model_name='professional',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed_professional',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.professional'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professional'),
        ),
        migrations.DeleteModel(
            name='Accountant',
        ),
    ]
