# Generated by Django 4.2.6 on 2023-11-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_professional_specialties_specialtiesaccountant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='password_hash',
        ),
    ]
