# Generated by Django 4.2.6 on 2023-11-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_professional_password_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='law_firm',
            new_name='firm_name',
        ),
    ]
