# Generated by Django 4.2.6 on 2023-11-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_law_firm_professional_firm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='consult_availability',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='credentials',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='fee_structure',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
