# Generated by Django 4.2.6 on 2023-11-07 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_education_professional_school_studied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='school_studied',
            new_name='school_studied_at',
        ),
    ]
