# Generated by Django 4.2.6 on 2023-11-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_school_studied_professional_school_studied_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
