# Generated by Django 4.2.6 on 2024-02-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_professional_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='location_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
