# Generated by Django 4.2.6 on 2024-02-17 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_forumquestion_forumanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumanswers',
            name='forum_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.forumquestion'),
        ),
    ]
