# Generated by Django 4.2.6 on 2024-02-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_forumanswers_forum_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='subscription_status',
            field=models.BooleanField(null=True),
        ),
    ]
