# Generated by Django 4.2.6 on 2024-02-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_professional_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumanswers',
            name='topics',
            field=models.ManyToManyField(to='core.specialties'),
        ),
    ]
