# Generated by Django 4.2.6 on 2024-02-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_forumanswers_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumanswers',
            name='topics',
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='topics',
            field=models.ManyToManyField(to='core.specialties'),
        ),
    ]
