# Generated by Django 4.2.6 on 2024-02-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumanswers',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
