# Generated by Django 4.2.6 on 2024-02-24 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_forumanswers_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumquestion',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.province'),
            preserve_default=False,
        ),
    ]
