# Generated by Django 4.2.6 on 2024-02-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_forumquestion_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
