# Generated by Django 4.2.6 on 2024-02-26 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_professional_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumquestion',
            name='location',
        ),
        migrations.RemoveField(
            model_name='forumquestion',
            name='topics',
        ),
        migrations.DeleteModel(
            name='ForumAnswers',
        ),
        migrations.DeleteModel(
            name='ForumQuestion',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
