# Generated by Django 4.2.6 on 2024-02-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_forumquestion_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='num_of_reviews',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
