# Generated by Django 4.2.6 on 2024-06-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_professional_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer_ip',
            field=models.GenericIPAddressField(default=0),
            preserve_default=False,
        ),
    ]
