# Generated by Django 4.2.6 on 2024-02-26 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0022_remove_forumquestion_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ForumQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_question_title', models.CharField(max_length=300)),
                ('forum_question', models.TextField()),
                ('view_count', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.province')),
                ('topics', models.ManyToManyField(to='core.specialties')),
            ],
        ),
        migrations.CreateModel(
            name='ForumAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True)),
                ('forum_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forumquestion')),
                ('professional_answered', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.professional')),
            ],
        ),
    ]
