# Generated by Django 4.2.6 on 2024-02-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumanswers',
            name='response',
            field=models.TextField(),
        ),
    ]
