# Generated by Django 4.2.6 on 2024-03-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_forumanswers_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumquestion',
            name='asker_email',
            field=models.EmailField(default='email@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
