# Generated by Django 4.2.6 on 2024-03-01 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('forum', '0003_forumquestion_asker_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumanswers',
            name='professional_answered',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.professional'),
        ),
        migrations.AlterField(
            model_name='forumquestion',
            name='topics',
            field=models.ManyToManyField(to='accounts.specialties'),
        ),
    ]
