# Generated by Django 4.2.6 on 2024-03-01 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_forumanswers_professional_answered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
