# Generated by Django 4.2.6 on 2024-03-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_forumquestion_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumquestion',
            name='resolved_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
