# Generated by Django 4.2.6 on 2024-03-03 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('forum', '0006_forumquestion_resolved_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumanswers',
            name='professional_answered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.professional'),
        ),
    ]
