# Generated by Django 4.2.6 on 2024-03-01 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('accountant', 'Accountant'), ('lawyer', 'Lawyer')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('firm_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('school_studied_at', models.TextField()),
                ('credentials', models.CharField(max_length=100)),
                ('experience_years', models.PositiveIntegerField()),
                ('fee_structure', models.TextField()),
                ('num_of_reviews', models.IntegerField()),
                ('average_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_long', models.FloatField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pictures/')),
                ('subscription_status', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('languages', models.ManyToManyField(to='accounts.languages')),
            ],
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.professional')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialtiesLawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.professional')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.specialties')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialtiesAccountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.professional')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.specialties')),
            ],
        ),
        migrations.AddField(
            model_name='professional',
            name='specialties',
            field=models.ManyToManyField(to='accounts.specialties'),
        ),
        migrations.AddField(
            model_name='professional',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
