# Generated by Django 4.2.6 on 2024-04-19 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_professional_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='profession',
        ),
    ]
