# Generated by Django 4.2.6 on 2024-04-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_professional_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='credentials',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='experience_years',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='fee_structure',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='firm_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='school_studied_at',
            field=models.TextField(null=True),
        ),
    ]
