# Generated by Django 4.2.6 on 2024-04-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_professional_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='school_studied_at',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
