# Generated by Django 4.2.6 on 2024-04-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_professional_school_studied_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='professional',
            name='credentials',
        ),
        migrations.AddField(
            model_name='professional',
            name='credentials',
            field=models.ManyToManyField(to='accounts.designations'),
        ),
    ]
