# Generated by Django 4.2.6 on 2024-04-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_designations_remove_professional_credentials_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='credentials',
            new_name='designations',
        ),
    ]
