# Generated by Django 4.2.6 on 2024-06-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_credentials_professional_designations'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='background_picture',
            field=models.ImageField(blank=True, default='/main/default-background.png', null=True, upload_to='profile_pictures/background_photos'),
        ),
    ]
