# Generated by Django 4.2.6 on 2024-06-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_professional_background_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='background_picture',
            field=models.ImageField(blank=True, default='/main/default-background.png', null=True, upload_to='profile_pictures/background_photos/'),
        ),
    ]
