# Generated by Django 4.2.6 on 2024-06-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_professional_background_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='unique_id',
            field=models.CharField(default=0, max_length=48),
            preserve_default=False,
        ),
    ]
