# Generated by Django 4.2.6 on 2024-06-28 21:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_professional_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='unique_id',
            field=models.CharField(default=accounts.models.generate_unique_id, max_length=48, unique=True),
        ),
    ]
