# Generated by Django 4.2.6 on 2024-03-04 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('forum', '0007_alter_forumanswers_professional_answered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=300)),
                ('blog_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.professional')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.province')),
                ('topics', models.ManyToManyField(to='accounts.specialties')),
            ],
        ),
    ]
