# Generated by Django 4.2.6 on 2024-03-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo_path',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
