# Generated by Django 4.2.6 on 2024-03-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('blog', '0003_blog_photo_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='topics',
        ),
        migrations.AddField(
            model_name='blog',
            name='topics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.specialties'),
            preserve_default=False,
        ),
    ]
