# Generated by Django 4.2.6 on 2024-03-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_topics_blog_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='topics',
            new_name='topic',
        ),
    ]
