# Generated by Django 4.2.6 on 2024-03-12 22:42

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_photo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo_path',
            field=models.ImageField(default=accounts.utils.get_random_blog_photo, upload_to=''),
        ),
    ]
