# Generated by Django 4.2.6 on 2024-03-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_len',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
