# Generated by Django 4.2.6 on 2024-03-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_blog_len'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
