# Generated by Django 4.2.6 on 2024-06-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
